plugins {
    id 'application'
    id 'java-common-conventions'
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }

    test {
        java {
            srcDirs = ['test']
        }
        resources {
            srcDirs = ['test/resources']
        }
    }
}

dependencies {
    implementation project(':MekWarsCommon')
    implementation project(':MekWarsClient')
}

application {
    mainClassName = 'mekwars.dedicatedhost.MWDedHost'
    applicationDefaultJvmArgs = [
            '-Xmx4096m',
            '-Dsun.awt.disablegrab=true'
    ]
}

ext {
    fileStagingDir = "${buildDir}/files"
    data = "data"
    docs = "docs"
    mmconf = "mmconf"
}

jar {
    archiveFileName = 'MekWarsDedicatedHost.jar'
    manifest {
        attributes(
          'Class-Path': "MegaMek.jar MekWars.jar " + configurations.runtimeClasspath.files
              .findAll { it.name.endsWith(".jar")
                && !it.name.toLowerCase().startsWith("megamek")
                && !it.name.toLowerCase().startsWith("mekwars")
              }
              .collect { "${lib}/${it.name}" }.join(' '),
          'Main-Class': mainClassName
        )
    }
}

task mekWarsBat(type: Copy) {
    if(!file(fileStagingDir).exists()) {
        file(fileStagingDir).mkdirs()
    }

    def jarTask = tasks.named('jar').get()
    def jvmArgs = (project.application.applicationDefaultJvmArgs ?: []).join(' ')
    def jarName = jarTask.archiveFileName.get()    // MekWars.jar
    def baseName = jarTask.archiveBaseName.get()   // MekWars

    File batFile = new File(fileStagingDir, "${baseName}.bat")
    batFile.text = "start /min javaw ${project.application.applicationDefaultJvmArgs.join(' ')} ${jar.archiveFileName.get()} -jar \"%~dp0MekWars.jar\" %*"
    from batFile
}

task stageFiles(type: Copy) {
    description = 'Stages files that are to be copied into the distribution.'
    dependsOn gradle.includedBuild('megamek').task(':megamek:stageFiles')

	from projectDir

	include "data/**"
	include "docs/**"
	include "mconf/**"
	include "userdata/**"

    into fileStagingDir
}

distributions {
    main {
        contents {
            from stageFiles
            from "${mmDir}/megamek/build/libs/MegaMek.jar"
            from "${mmDir}/megamek/build/files"
            from jar
            from project(':MekWarsClient').jar
            copy {
                from  mekWarsBat
                into "."
            }
            from (project.sourceSets.main.runtimeClasspath.files
                    .findAll { it.name.endsWith(".jar") }) {
                into "${lib}"
            }
            from "${mmDir}/megamek/build/files/mechfiles"
            duplicatesStrategy = 'exclude'
        }
    }
}

test {
    jvmArgs "-Dlog4j2.configurationFile=log4j2.xml"
    useJUnitPlatform()
}
