plugins {
	id 'java-library'
}

dependencies {
	implementation "org.megamek:megamek:${mmVersion}"

	implementation 'org.quartz-scheduler:quartz:2.2.3'
	implementation 'org.apache.logging.log4j:log4j-core:2.25.2'
	implementation 'org.apache.logging.log4j:log4j-api:2.25.2'
    implementation 'org.apache.logging.log4j:log4j-slf4j-impl:2.25.2'
	implementation 'com.thoughtworks.xstream:xstream:1.4.21'
	implementation 'com.esotericsoftware:kryo:5.6.2'

    testImplementation "org.mockito:mockito-junit-jupiter:5.11.0"
    testImplementation 'org.mockito:mockito-core:5.11.0'
    testImplementation "org.junit.jupiter:junit-jupiter:5.10.2"
}

application {
    applicationDefaultJvmArgs = [
			'-Dlog4j2.configurationFile=log4j2.xml',
            '-Xmx4096m',
            '-Dsun.awt.disablegrab=true'
    ]
}

test {
    testLogging {
        events "failed"
        exceptionFormat "full"
        showExceptions true
        showCauses true
        showStackTraces true
        showStandardStreams = true
    }
}

tasks.register("generateMigration") {
    group = "flyway"
    description = "Generates a new Flyway migration file with a LocalDateTime version"

    doLast {
        if (!project.hasProperty("migration_name")) {
            throw new GradleException("Migration name is required. Please provide one using -Pmigration_name=<migration_name>")
        }

        def migrationName = project.findProperty("migration_name").trim()
        def timestamp = LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern('yyyyMMdd_HHmmss'))
        println migrationName
        def filename = "V${timestamp}__${migrationName}.sql"

        def migrationsDir
        switch (project.name) {
            case 'MekWarsServer':
                migrationsDir =
                    file('src/main/resources/db/migration/server')
                break
            case 'MekWarsClient':
                migrationsDir =
                    file('src/main/resources/db/migration/client')
                break
            case 'MekWarsCommon':
                migrationsDir =
                    file('src/main/resources/db/migration/common')
                break
            default:
                throw new GradleException("Unknown project '${project.name}'. Expected: MekWarsServer, MekWarsClient, or MekWarsCommon.")
            }

        migrationsDir.mkdirs()

        def migrationFile = new File(migrationsDir, filename)
        migrationFile.text = "-- Migration: ${migrationName}\n-- Created: ${new Date()}\n\n"

        println "Created migration: ${migrationFile.path}"
    }
}
