errors.noOpList.text=No OpList. This usually means that you were unable to connect to the server to fetch a copy. Do you wish to exit?
errors.badConfigDir.text=Unable to set the configuration directory, please check the application can create the directory '{0}'
errors.header.text=Startup Error!
options.exit.text=Exit
options.continue.text=Continue
