/*
 * Created on 21.05.2004
 */

/*
 * MekWars - Copyright (C) 2004
 *
 * Derived from MegaMekNET (http://www.sourceforge.net/projects/megameknet)
 * Original author Helge Richter (McWizard)
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 */

package mekwars.client.campaign;

import mekwars.client.MWClient;
import mekwars.common.Army;
import mekwars.common.Unit;
import mekwars.common.util.TokenReader;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.StringTokenizer;

/**
 * Client-side representation of an Army. The CArmy has, when compared to its server-side
 * counterpart, very few functional methods, and mostly serves as a holder for server data that the
 * client needs in order to represent forces graphically, load units into games, etc.
 */
@jakarta.persistence.Entity
public class CArmy extends Army<CUnit> {
    /**
     * Method that fills in Army data (common.Army value), given an informational String. Called
     * from CPlayer.setArmyData() and CPlayer.setData(). In both instances, the string being passed
     * is generated by the server and sent down using a PL| cmd.
     */
    public void fromString(String s, CPlayer p, String delimiter, MWClient client) {
        StringTokenizer ST = new StringTokenizer(s, delimiter);
        setId(TokenReader.readInt(ST));
        setBV(TokenReader.readInt(ST));
        setLocked(TokenReader.readBoolean(ST));
        setName(TokenReader.readString(ST));
        setLowerLimiter(TokenReader.readInt(ST));
        setUpperLimiter(TokenReader.readInt(ST));
        int count = TokenReader.readInt(ST);
        for (int i = 0; i < count; i++) {
            CUnit unit = p.getUnit(TokenReader.readInt(ST));

            // do not add units with id 0 as their id has already been replaced
            // --Torren
            if (unit.getId() != 0) {
                addUnit(unit);
            }
        }

        count = TokenReader.readInt(ST);
        for (int i = 0; i < count; i++) {
            int key = TokenReader.readInt(ST);
            int unit = TokenReader.readInt(ST);
            getC3Network().put(key, unit);
        }

        this.setOpForceSize(TokenReader.readFloat(ST));

        count = TokenReader.readInt(ST);
        for (int i = 0; i < count; i++) {
            int unit = TokenReader.readInt(ST);
            addCommander(unit);
        }

        boolean locked = TokenReader.readBoolean(ST);
        if (locked) {
            playerLockArmy();
        } else {
            playerUnlockArmy();
        }
        boolean disabled = TokenReader.readBoolean(ST);
        if (disabled) {
            disableArmy();
        } else {
            enableArmy();
        }
    }

    public String getSkillInfoForDisplay() {
        if (this.getUnits().size() < 1) {
            return " ";
        }

        String avgSkills = "0.0";
        String avgGunnery = "0.0";
        String avgPiloting = "0.0";
        int maxSkill = 0;
        int maxGunnery = 0;
        int maxPiloting = 0;
        int minSkill = 99;
        int minGunnery = 99;
        int minPiloting = 99;
        int numunits = 0;
        int totalGunnery = 0;
        int totalPiloting = 0;
        StringBuilder toReturn = new StringBuilder();
        for (Unit un : this.getUnits()) {
            CUnit unit = (CUnit) un;
            int gunnery = unit.getPilot().getGunnery();
            int piloting = unit.getPilot().getPiloting();
            maxSkill = Math.max(maxSkill, (gunnery + piloting));
            maxGunnery = Math.max(maxGunnery, gunnery);
            maxPiloting = Math.max(maxPiloting, piloting);
            minSkill = Math.min(minSkill, (gunnery + piloting));
            minGunnery = Math.min(minGunnery, gunnery);
            minPiloting = Math.min(minPiloting, piloting);
            totalGunnery += gunnery;
            totalPiloting += piloting;
            numunits++;
        }
        // Need to use a DecimalFormat so we don't get just whole integer averages

        double avgS = (double) (totalGunnery + totalPiloting) / (double) numunits;
        double avgG = (double) (totalGunnery) / (double) numunits;
        double avgP = (double) (totalPiloting) / (double) numunits;
        DecimalFormat twoDForm = (DecimalFormat) NumberFormat.getNumberInstance();
        twoDForm.applyPattern("0.00");

        avgSkills = twoDForm.format(avgS);
        avgGunnery = twoDForm.format(avgG);
        avgPiloting = twoDForm.format(avgP);

        toReturn.append("<html><table><tr><td colspan=4>Skillsums</td></tr>");
        toReturn.append("<tr><td>&nbsp;</td><td>Total</td><td>Gunnery</td><td>Piloting</td></tr>");
        toReturn.append(
                "<tr><td>Average:</td><td>"
                        + avgSkills
                        + "</td><td>"
                        + avgGunnery
                        + "</td><td>"
                        + avgPiloting
                        + "</td></tr>");
        toReturn.append(
                "<tr><td>Maximum:</td><td>"
                        + maxSkill
                        + "</td><td>"
                        + maxGunnery
                        + "</td><td>"
                        + maxPiloting
                        + "</td></tr>");
        toReturn.append(
                "<tr><td>Minimum:</td><td>"
                        + minSkill
                        + "</td><td>"
                        + minGunnery
                        + "</td><td>"
                        + minPiloting
                        + "</td></tr>");
        toReturn.append("</table></html>");
        return toReturn.toString();
    }
}
