/*
 * MekWars - Copyright (C) 2004
 *
 * Derived from MegaMekNET (http://www.sourceforge.net/projects/megamek)
 * Original author Helge Richter (McWizard)
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 */

package mekwars.client.campaign;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.StringTokenizer;
import java.util.TreeMap;

import mekwars.client.MWClient;
import mekwars.client.GUIClient;
import mekwars.client.gui.CCommPanel;
import mekwars.client.gui.dialog.ArmyViewerDialog;
import mekwars.common.BMEquipment;
import mekwars.common.CampaignData;
import mekwars.common.util.ComponentToCritsConverter;
import mekwars.common.util.TokenReader;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import megamek.common.OffBoardDirection;

/**
 * Class for Campaign object used by Client
 * TODO: Rewrite command decoding. Its crazy right now.
 * TODO: Properly comment this class.
 */
public class CCampaign {
    private static final Logger LOGGER = LogManager.getLogger(CCampaign.class);

    MWClient mwclient;
    CPlayer Player;
    TreeMap<Integer,CBMUnit> BlackMarket = new TreeMap<Integer,CBMUnit>();
    TreeMap<String,BMEquipment> BlackMarketParts = new TreeMap<String, BMEquipment>();
    TreeMap<String, ComponentToCritsConverter> ComponentConverter = new TreeMap<String, ComponentToCritsConverter>();
    private List<CUnit> autoArmy;

    public CCampaign(MWClient client) {
        mwclient = client;
        Player = new CPlayer();
    }

    /**
     * Method that reads data generated by Market2.getAutoMarketStatus()
     * on the server. All data for all BM units sent at once. "|" used
     * to seperate units, * used to seperate fields inside each unit.
     */
    public void setBMData(String command) {

        //create tokenizer
        StringTokenizer mainTokenizer = new StringTokenizer(command, "$");

        //clear all current BM data
        BlackMarket.clear();

        while(mainTokenizer.hasMoreTokens()) {
            boolean hidden = Boolean.parseBoolean(mwclient.getServerConfigs("HiddenBMUnits"));
            CBMUnit currBMUnit = new CBMUnit(TokenReader.readString(mainTokenizer), this, hidden);
            BlackMarket.put(currBMUnit.getAuctionID(), currBMUnit);
        }
    }

    /**
     * Method that removes a unit from the Client's BM representation.
     */
    public void removeBMUnit(String command) {
        BlackMarket.remove(Integer.valueOf(command));
    }

    /**
     * Method that adds a unit to the client's BM representation.
     */
    public void addBMUnit(String command) {
        CBMUnit bmUnit = new CBMUnit(command, this, Boolean.parseBoolean(mwclient.getServerConfigs("HiddenBMUnits")));
        BlackMarket.put(bmUnit.getAuctionID(), bmUnit);
    }

    /**
     * Method that repaces a CBMUnit. Called after a player bids
     * on a unit in order to change colors and show amount.
     */
    public void changeBMUnit(String command) {
        CBMUnit bmUnit = new CBMUnit(command, this, Boolean.parseBoolean(mwclient.getServerConfigs("HiddenBMUnits")));
        BlackMarket.remove(bmUnit.getAuctionID());
        BlackMarket.put(bmUnit.getAuctionID(), bmUnit);
    }

    public boolean showMsg(String command) {
        return true;
    }

    public boolean showStatus(String command) {
        mwclient.getGUIClient().addToChat(command);
        return true;
    }

    //public MWClient getClient() {return mwclient;}
    public void setPlayer(CPlayer tplayer) {Player = tplayer;}
    public CPlayer getPlayer() {return Player;}
    public TreeMap<Integer,CBMUnit> getBlackMarket() {return BlackMarket;}

    public TreeMap<String,BMEquipment> getBlackMarketParts() { return BlackMarketParts; }

    public TreeMap<String, ComponentToCritsConverter> getComponentConverter() { return ComponentConverter; }

    public void setComponentConverter(String converterData) {
        try {
            StringTokenizer st = new StringTokenizer(converterData,"#");

            ComponentConverter.clear();
            while (st.hasMoreTokens()) {
                ComponentToCritsConverter converter = new ComponentToCritsConverter();
                converter.setCriticalName(TokenReader.readString(st));
                converter.setMinCriticalLevel(TokenReader.readInt(st));
                converter.setComponentUsedType(TokenReader.readInt(st));
                converter.setComponentUsedWeight(TokenReader.readInt(st));
                ComponentConverter.put(converter.getCriticalName(), converter);
            }
            mwclient.setWaiting(false);
        } catch(Exception ex) {
            LOGGER.error("Exception: ", ex);
        }
    }

    /**
     * Method which returns the autoArmy arraylist.
     */
    public List<CUnit> getAutoArmy() {
        return autoArmy;
    }

    /**
     * Method which greates an autoarmy. takes in a string with weight classes,
     * and uses server configs (path, filenames) to construct units of those
     * weights.
     *
     * Units are added to servers when a player joins a game, same as units from
     * locked armies.
     */
    public void setAutoArmy(StringTokenizer st) {
        /*
         * clear the previous autoarmy. Auto army is always called first, and is
         * cleared correctly even if only gun emplacements are sent.
         */
        autoArmy = new ArrayList<CUnit>();

        // if its a null, this was just a clearing call.
        if (st == null) {
            return;
        }

        while (st.hasMoreTokens()) {
            String filename = TokenReader.readString(st);
            if (filename.equals("CLEAR")) {
                return;
            }

            // get the distance
            int distInBoards = CampaignData.cd.getCampaignOptions().getIntegerConfig("DistanceFromMap");
            int distInHexes = distInBoards * 17;// 17 hexes per board.

            CUnit currUnit = new CUnit();

            /*
             * This is needed to set the edge for auto arty when auto edge is
             * set for players. Else, arty edge is set in MM when the players
             * click on the edge they want.
             */
            OffBoardDirection direction = OffBoardDirection.NORTH;
            switch (mwclient.getPlayerStartingEdge()) {
                case 0:
                    break;
                case 1:
                case 2:
                case 3:
                    direction = OffBoardDirection.NORTH;
                    break;
                case 4:
                    direction = OffBoardDirection.EAST;
                    break;
                case 5:
                case 6:
                case 7:
                    direction = OffBoardDirection.SOUTH;
                    break;
                case 8:
                    direction = OffBoardDirection.WEST;
                    break;
            }

            currUnit.setAutoUnitData(getPlayer().getMyHouse(), filename, distInHexes, direction);
            autoArmy.add(currUnit);
        }
    }

    public void setMULCreatedArmy(StringTokenizer st) {
        while (st.hasMoreElements()) {
            String data = TokenReader.readString(st);
            if (data.equalsIgnoreCase("CLEAR")) {
                return;
            }

            CUnit cm = new CUnit();
            cm.setData(data);
            autoArmy.add(cm);
        }
    }

    /**
     * Method which greates an autoarmy gun emplacements. takes in a string with
     * weight classes, and uses server configs (path, filenames) to construct
     * units of those weights.
     *
     * Units are added to servers when a player joins a game, same as units from
     * locked armies.
     */
    public void setAutoGunEmplacements(StringTokenizer st) {
        // if its a null, this was just a clearing call.
        if (st == null) {
            return;
        }

        while (st.hasMoreTokens()) {
            String filename = TokenReader.readString(st);
            if (filename.equals("CLEAR")) {
                return;
            }

            CUnit currUnit = new CUnit();
            currUnit.setAutoUnitData(getPlayer().getMyHouse(), filename, 0, OffBoardDirection.NORTH);
            autoArmy.add(currUnit);
        }// end while(tokens)
    }// end setAutoArmy()
}
