/*
 * MekWars - Copyright (C) 2004
 *
 * Derived from MegaMekNET (http://www.sourceforge.net/projects/megamek)
 * Original author Helge Richter (McWizard)
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 */

package mekwars.client.campaign;

import java.io.File;
import java.util.StringTokenizer;
import java.util.TreeMap;

import mekwars.client.MWClient;
import mekwars.client.GUIClient;
import mekwars.client.gui.CCommPanel;
import mekwars.client.gui.dialog.ArmyViewerDialog;
import mekwars.common.BMEquipment;
import mekwars.common.util.ComponentToCritsConverter;
import mekwars.common.util.TokenReader;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Class for Campaign object used by Client
 * TODO: Rewrite command decoding. Its crazy right now.
 * TODO: Properly comment this class.
 */
public class CCampaign {
    private static final Logger LOGGER = LogManager.getLogger(CCampaign.class);

    MWClient mwclient;
    CPlayer Player;
    TreeMap<Integer,CBMUnit> BlackMarket = new TreeMap<Integer,CBMUnit>();
    TreeMap<String,BMEquipment> BlackMarketParts = new TreeMap<String, BMEquipment>();
    TreeMap<String, ComponentToCritsConverter> ComponentConverter = new TreeMap<String, ComponentToCritsConverter>();
    private List<CUnit> autoArmy;

    public CCampaign(MWClient client) {
        mwclient = client;
        Player = new CPlayer(mwclient);
    }

    /**
     * Method that reads data generated by Market2.getAutoMarketStatus()
     * on the server. All data for all BM units sent at once. "|" used
     * to seperate units, * used to seperate fields inside each unit.
     */
    public void setBMData(String command) {

        //create tokenizer
        StringTokenizer mainTokenizer = new StringTokenizer(command, "$");

        //clear all current BM data
        BlackMarket.clear();

        while(mainTokenizer.hasMoreTokens()) {
            boolean hidden = Boolean.parseBoolean(mwclient.getServerConfigs("HiddenBMUnits"));
            CBMUnit currBMUnit = new CBMUnit(TokenReader.readString(mainTokenizer), this, hidden);
            BlackMarket.put(currBMUnit.getAuctionID(), currBMUnit);
        }
    }

    /**
     * Method that removes a unit from the Client's BM representation.
     */
    public void removeBMUnit(String command) {
        BlackMarket.remove(Integer.valueOf(command));
    }

    /**
     * Method that adds a unit to the client's BM representation.
     */
    public void addBMUnit(String command) {
        CBMUnit bmUnit = new CBMUnit(command, this, Boolean.parseBoolean(mwclient.getServerConfigs("HiddenBMUnits")));
        BlackMarket.put(bmUnit.getAuctionID(), bmUnit);
    }

    /**
     * Method that repaces a CBMUnit. Called after a player bids
     * on a unit in order to change colors and show amount.
     */
    public void changeBMUnit(String command) {
        CBMUnit bmUnit = new CBMUnit(command, this, Boolean.parseBoolean(mwclient.getServerConfigs("HiddenBMUnits")));
        BlackMarket.remove(bmUnit.getAuctionID());
        BlackMarket.put(bmUnit.getAuctionID(), bmUnit);
    }

    public boolean showMsg(String command) {
        return true;
    }

    public boolean showStatus(String command) {
        mwclient.getGUIClient().addToChat(command);
        return true;
    }

    //public MWClient getClient() {return mwclient;}
    public void setPlayer(CPlayer tplayer) {Player = tplayer;}
    public CPlayer getPlayer() {return Player;}
    public TreeMap<Integer,CBMUnit> getBlackMarket() {return BlackMarket;}

    public TreeMap<String,BMEquipment> getBlackMarketParts() { return BlackMarketParts; }

    public TreeMap<String, ComponentToCritsConverter> getComponentConverter() { return ComponentConverter; }

    public void setComponentConverter(String converterData) {
        try {
            StringTokenizer st = new StringTokenizer(converterData,"#");

            ComponentConverter.clear();
            while (st.hasMoreTokens()) {
                ComponentToCritsConverter converter = new ComponentToCritsConverter();
                converter.setCritName(TokenReader.readString(st));
                converter.setMinCritLevel(TokenReader.readInt(st));
                converter.setComponentUsedType(TokenReader.readInt(st));
                converter.setComponentUsedWeight(TokenReader.readInt(st));
                ComponentConverter.put(converter.getCritName(), converter);
            }
            mwclient.setWaiting(false);
        }catch(Exception ex) {
            LOGGER.error("Exception: ", ex);
        }
    }
}
