plugins {
    id 'application'
        id 'java-common-conventions'
        id 'org.flywaydb.flyway' version "8.5.7"
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }

    test {
        java {
            srcDirs = ['unittests']
        }
        resources {
            srcDirs = ['unittests/resources']
        }
    }
}

dependencies {
    implementation 'org.hibernate.orm:hibernate-platform:6.6.50.Final'
    implementation 'org.hibernate.orm:hibernate-community-dialects:6.6.50.Final'
    implementation 'org.hibernate.common:hibernate-commons-annotations:6.0.6.Final'
    implementation 'jakarta.transaction:jakarta.transaction-api'
    implementation 'org.xerial:sqlite-jdbc:3.53.0.0'
    implementation 'org.flywaydb:flyway-core:9.22.3'
  
    annotationProcessor 'org.hibernate.orm:hibernate-jpamodelgen:6.6.50.Final'
}

application {
    applicationDefaultJvmArgs = [
        '-Dlog4j2.configurationFile=log4j2.xml',
        '-Xmx4096m',
        '-Dsun.awt.disablegrab=true'
    ]
}

ext {
    data = "data"
    docs = "docs"
    mmconf = "mmconf"
}

test {
    jvmArgs "-Dlog4j2.configurationFile=log4j2.xml"
    useJUnitPlatform()
}
